### ISSUE TITLE
Tweak readme

### ISSUE THREAD

**Issue by vweevers** [Level/encoding-down#15]
- [x] Rewrite short description, the current only describes history
- [x] Explain what encodings do, perhaps with an example
- [ ] Explain how it relates to serialization and storage
- [x] `const` -> `var`
- [x] `const db = ..` -> `db = ..` in api header

See https://github.com/Level/levelup/issues/456#issuecomment-335002055

**Comment by ralphtheninja** [comment]
@vweevers Up for taking on the last point in the list before we release new version?

**Comment by vweevers** [comment]
Hmm, I don't think serialization is documented anywhere, and it should be, but is encoding-down the best place? Perhaps we should start with documentation in `abstract-leveldown` and then link to it from here.

**Comment by ralphtheninja** [comment]
> Hmm, I don't think serialization is documented anywhere, and it should be, but is encoding-down the best place? Perhaps we should start with documentation in abstract-leveldown and then link to it from here.

Agreed. Do whatever you feel is best :smile:

**Comment by ralphtheninja** [comment]
@vweevers I update the `const` to `var` stuff. Feel like finishing off the last point?
