### ISSUE TITLE
pass on asBuffer property to underlying store depending on which encoding

### ISSUE THREAD

**Issue by ralphtheninja** [Level/encoding-down#18]
See https://github.com/Level/levelup/issues/515 for background

- [x] add failing tests
- [x] fix failing tests

**Comment by ralphtheninja** [comment]
First idea for a test that came into my mind was to

* grab all the encodings from `level-codec`
* call functions on a mock *down and make sure `options.asBuffer` is set to `true` or `false` as expected

**Comment by vweevers** [comment]
Minimal repro to get us started:

```js
'use strict'

const test = require('tape')
const encdown = require('..')
const noop = function () {}

test('string encoding retrieves a string from underlying store', function (t) {
  t.plan(1)

  const down = {
    get: function (key, options, cb) {
      t.is(options.asBuffer, false) // This fails
    }
  }

  const db = encdown(down, {
    valueEncoding: {
      buffer: false
    }
  })

  db.get('key', noop)
})
```

**Comment by vweevers** [comment]
After fixing this, we can maybe also revert Level/codec#12. @juliangruber WDYT?

**Comment by juliangruber** [comment]
:+1:

**Comment by vweevers** [comment]
@ralphtheninja can you take this on? I'll finish the documentation but am already on stolen time :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja can you take this on? I'll finish the documentation but am already on stolen time :)

Will do!
