### ISSUE TITLE
Ensure that remark encodes colons properly

### ISSUE THREAD

**Issue by ralphtheninja** [Level/encoding-down#59]
Just a place holder. Close this once we can do `npm run remark` without encoding encoded colon again.

See https://github.com/Level/encoding-down/pull/57#issuecomment-399417399

**Comment by vweevers** [comment]
I think it's https://github.com/remarkjs/remark/tree/master/packages/remark-stringify#optionsgfm

**Comment by vweevers** [comment]
Scratch that, disabling `gfm` doesn't change the colon behavior:

```json
"remarkConfig": {
    "settings": {
      "gfm": false
    },
    ..
 }
```

**Comment by vweevers** [comment]
Might be a parser bug, because ` foo:` is not encoded.

**Comment by vweevers** [comment]
Ah, maybe because it tries to parse this as a bookmark?

**Comment by vweevers** [comment]
Found it: [a colon is escaped if it follows a `linkReference` node of type `shortcut`](https://github.com/remarkjs/remark/blob/02297a5dea290751a0bfd766b4154ad403307b7e/packages/remark-stringify/lib/escape.js#L140).

So escaping `:` is a feature, but the double escaping is a bug.

**Comment by vweevers** [comment]
From what I understand, `remark-parse` is supposed to decode entities.

It doesn't do this for `&#x3A;` though. It parses `foo &amp; &#x3A;` as:

```json
[          
  {                    
    "type": "text",
    "value": "foo "          
  },                   
  {                    
    "type": "text",
    "value": "&"                
  },                   
  {                    
    "type": "text",    
    "value": " &#x3A;"
  }
]
```

**Comment by vweevers** [comment]
Oh god this is a rabbit hole.

@ralphtheninja we can circumvent it for now by using a full link reference. PR coming up.
