### ISSUE TITLE
Promise/async support for custom encoder?

### ISSUE THREAD

**Issue by jkroepke** [Level/encoding-down#95]
Is Promise/async supported?

I'm want to use 3rd party libraries to modify values on read and write. The library expose the functions as promise. Can I use this with encoding-down?

Like

```
{
  encode: async function (data) {
    return jose.JWE.createEncrypt({ format: 'compact' }, key).update(input).final();
  },
  decode: async function (data) {
    return jose.JWE.createDecrypt(key).decrypt(input)
  },
  buffer: Boolean,
  type: 'example'
}
```

Or are old style callback planned?

```
{
  encode: function (data, cb) {
    return jose.JWE.createEncrypt({ format: 'compact' }, key).update(input).final().then(function(result) {
      cb(result)
    });
  },
  decode: function (data, cb) {
    return jose.JWE.createDecrypt(key).decrypt(input).then(function(result) {
      cb(result)
    });
  },
  buffer: Boolean,
  type: 'example'
}
```

**Comment by vweevers** [comment]
Codecs are synchronous and that can't change unfortunately. For some methods like `get()` and `put()` it would be possible, but the codec is also used to encode range options (like `gte`), for example when creating an iterator:

https://github.com/Level/encoding-down/blob/6c475ff8c536f7de3e5729f62db5946f676cc87c/index.js#L110-L117

Making that asynchronous would break snapshot guarantees, which in a nutshell guarantees that the iterator reads from a snapshot in time, unaffected by writes made in the mean time.
